### PR TITLE
Fix parse case of empty string with headers true

### LINKED ISSUE #64: `CSV.parse('', headers: true)` was broken?
If `headers: true` option was given, `CSV.parse()` returns `CSV::Table` object even if empty string will be passed as argument with Ruby 2.5.0.

However, in Ruby 2.6, the above behavior was incomatible. 

I want to know whether it is expected. Thank you!!

### Ruby 2.6

```
$ ruby -v ttt.rb
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
[]
Traceback (most recent call last):
ttt.rb:4:in `<main>': undefined method `headers' for []:Array (NoMethodError)
```

### Ruby 2.5

```
$ ruby -v ttt.rb
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
#<CSV::Table mode:col_or_row row_count:1>
[]
```

### Test code
```ruby
require 'csv'
row = CSV.parse('', headers: true)
p row
p row.headers
```

### PR DESCRIPTION
**Pull request by 284km**
Fix #64

In this case "undefined method `headers' for []:Array (NoMethodError)"
was occurring.

```
row = CSV.parse('', headers: true)
p row
p row.headers
```

when CSV.parse with (headers: true) option,
return CSV::Table class is expected, but it was returned Array as below.

```
def read
  rows = to_a #=> []
  headers = parser.headers #=> nil
  if headers
    Table.new(rows, headers: headers)
  else
    rows
  end
end
```

### CODE REVIEW

**Comment by kou** [comment]
We shouldn't return `Table` when `headers:` isn't specified.

**Comment by 284km** [comment]
I understand. Changed to judge by CSV::Parser#use_headers.

File: lib/csv.rb [hunk 1]
```diff
@@ -1179,7 +1179,7 @@ def each(&block)
   def read
     rows = to_a
     headers = parser.headers
-    if headers
+    if headers || parser.use_headers
```
Comment (kou) [inline lib/csv.rb]: Can we remove `headers ||`?

File: test/csv/test_headers.rb [hunk 2]
```diff
@@ -315,4 +315,9 @@ def test_nil_row_header
     assert_equal([["A"], [nil]],
                  [row.headers, row.fields])
   end
+
+  def test_empty_string_value_with_headers_true
+    row = CSV.parse('', headers: true)
```
Comment (kou) [inline test/csv/test_headers.rb]: It must be `table`.

File: test/csv/test_headers.rb [hunk 3]
```diff
@@ -315,4 +315,9 @@ def test_nil_row_header
...
+    assert_equal([], row.headers)
```
Comment (kou) [inline test/csv/test_headers.rb]: `assert_equal(CSV::Table.new([], []), table)` is better because it shows more information (such as class ans instance variables) on failure.

FYI: https://www.clear-code.com/blog/2011/2/28.html

File: lib/csv/parser.rb [hunk 4]
```diff
@@ -289,6 +289,10 @@ def parse(&block)
       end
     end
 
+    def use_headers
```
Comment (kou) [inline lib/csv/parser.rb]: `use_headers?` is better.

File: lib/csv.rb (hunk 1 above)
Comment (284km) [reply lib/csv.rb]: Yes. Only parser.use_headers? is enough condition.

File: test/csv/test_headers.rb (hunk 2 above)
Comment (284km) [reply test/csv/test_headers.rb]: Fixed it.

File: test/csv/test_headers.rb (hunk 3 above)
Comment (284km) [reply test/csv/test_headers.rb]: Thank you for information. Fixed it.

File: lib/csv/parser.rb (hunk 4 above)
Comment (284km) [reply lib/csv/parser.rb]: Definedly. Fixed it.
